#include "Plans/constraints/ProvideSupplies1484927081537Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1484927081537) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:ProvideSupplies

/*		
 * Tasks: 
 * - EP:1484927081539 : DefaultTask (1414681164704)
 *
 * States:
 * - Success (1484927117903)
 * - FindSupplies (1484927333656)
 * - LoadSupplies (1484927341401)
 * - FindVictim (1484927352148)
 * - ProvideSupplies (1484927371709)
 *
 * Vars:
 */

// State: Success

// State: Success

// State: FindSupplies

// State: FindSupplies

// State: LoadSupplies

// State: LoadSupplies

// State: FindVictim

// State: FindVictim

// State: ProvideSupplies

// State: ProvideSupplies

}
