#include "ConditionCreator.h"

#include  "Plans/ProvideSupplies1484927081537.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    shared_ptr<BasicCondition> ConditionCreator::createConditions(long conditionConfId)
    {
        switch (conditionConfId)
        {

            case 1484927391389:

                return make_shared<TransitionCondition1484927391389>();

                break;

            case 1484927394940:

                return make_shared<TransitionCondition1484927394940>();

                break;

            case 1484927401848:

                return make_shared<TransitionCondition1484927401848>();

                break;

            case 1484927426260:

                return make_shared<TransitionCondition1484927426260>();

                break;

            case 1484927433844:

                return make_shared<TransitionCondition1484927433844>();

                break;

            default:
                cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << endl;
                throw new exception();
                break;
        }
    }
}
