#ifndef ProvideSuppliesCONSTRAINT_H_
#define ProvideSupplies_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* ProvideSuppliesCONSTRAINT_H_ */
